//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 414
namespace eRechnung {
    
    
    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name="FullTrust")]
    public sealed partial class ThisDocument : Microsoft.Office.Tools.Word.DocumentBase {
        
        internal Microsoft.Office.Tools.ActionsPane ActionsPane;
        
        internal Microsoft.Office.Tools.Word.Bookmark b00;
        
        internal Microsoft.Office.Tools.Word.Bookmark b01;
        
        internal Microsoft.Office.Tools.Word.Bookmark b02;
        
        internal Microsoft.Office.Tools.Word.Bookmark b03;
        
        internal Microsoft.Office.Tools.Word.Bookmark b04;
        
        internal Microsoft.Office.Tools.Word.Bookmark b05;
        
        internal Microsoft.Office.Tools.Word.Bookmark b06;
        
        internal Microsoft.Office.Tools.Word.Bookmark b07;
        
        internal Microsoft.Office.Tools.Word.Bookmark b08;
        
        internal Microsoft.Office.Tools.Word.Bookmark b09;
        
        internal Microsoft.Office.Tools.Word.Bookmark b10;
        
        internal Microsoft.Office.Tools.Word.Bookmark b11;
        
        internal Microsoft.Office.Tools.Word.Bookmark b12;
        
        internal Microsoft.Office.Tools.Word.Bookmark b13;
        
        internal Microsoft.Office.Tools.Word.Bookmark b16;
        
        internal Microsoft.Office.Tools.Word.Bookmark b17;
        
        internal Microsoft.Office.Tools.Word.Bookmark b18;
        
        internal Microsoft.Office.Tools.Word.Bookmark b19;
        
        internal Microsoft.Office.Tools.Word.Bookmark b21;
        
        internal Microsoft.Office.Tools.Word.Bookmark b22;
        
        internal Microsoft.Office.Tools.Word.Bookmark b23;
        
        internal Microsoft.Office.Tools.Word.Bookmark b24;
        
        internal Microsoft.Office.Tools.Word.Bookmark bLiefNr;
        
        internal Microsoft.Office.Tools.Word.Bookmark b26;
        
        internal Microsoft.Office.Tools.Word.Bookmark b27;
        
        internal Microsoft.Office.Tools.Word.Bookmark b28;
        
        internal Microsoft.Office.Tools.Word.DropDownListContentControl CC_InvoiceDocType;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_BillerName;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_BillerStreet;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_BillerPlz;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_BillerTown;
        
        internal Microsoft.Office.Tools.Word.DropDownListContentControl CC_BillerCountry;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_BillerGln;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_BillerContact;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_BillerPhone;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_BillerMail;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_BillerVatID;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_RecSalutation;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_RecName;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_RecStreet;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_RecPlz;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_RecTown;
        
        internal Microsoft.Office.Tools.Word.DropDownListContentControl CC_RecCountry;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_RecGln;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_RecContact;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_RecPhone;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_RecMail;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_RecVatID;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_InTitle;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_LiefantenNr;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_KundenNr;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_InvNr;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl CC_InvDate;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_OrderReference;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl CC_OrderDate;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_SubOrganisation;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_AcctArea;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl CC_LieferDatum;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_Kopftext;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_InvTotalNetAmountText;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_InvTotalNetAmount;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_InvTaxText;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_InvTaxAmount;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_InvTotalAmountText;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_InvTotalAmount;
        
        internal Microsoft.Office.Tools.Word.DropDownListContentControl CC_InvCurrency;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl CC_InvDueDate;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_KtoBankName;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_KtoBic;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_KtoIBAN;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_KtoOwner;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_KtoReference;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_Fusstext;
        
        internal Microsoft.Office.Tools.Word.Bookmark b98;
        
        internal Microsoft.Office.Tools.Word.Bookmark b14;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_DocComment;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_DocRef;
        
        internal Microsoft.Office.Tools.Word.DropDownListContentControl CC_RefType;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_RefInvNr;
        
        internal Microsoft.Office.Tools.Word.DatePickerContentControl CC_RefInvDate;
        
        internal Microsoft.Office.Tools.Word.PlainTextContentControl CC_RefComment;
        
        internal Microsoft.Office.Tools.Word.DropDownListContentControl CC_RefDocType;
        
        internal Microsoft.Office.Tools.Word.Bookmark bEmpfMail;
        
        internal Microsoft.Office.Tools.Word.Bookmark b30Formular;
        
        internal Microsoft.Office.Tools.Word.Bookmark bkmkFormular;
        
        internal Microsoft.Office.Tools.Word.Bookmark bHeadline;
        
        internal Microsoft.Office.Tools.Word.Bookmark bestpos;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        private global::System.Object missing = global::System.Type.Missing;
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        internal Microsoft.Office.Interop.Word.Application ThisApplication;
        
        private System.ComponentModel.IContainer components;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmInvTypeDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmBillerNameDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmBillerStreetDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmBillerPlzDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmBillerTownDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmBillerCountryDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmBillerGlnDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmBillerContactDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmbillerphoneDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmbillermailDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmbillervatidDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmrecsalutationDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmrecnameDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmrecstreetDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmrecplzDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmrectownDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmreccountryDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmrecglnDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmreccontactDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmrecphoneDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmrecmailDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmrecvatidDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmintitleDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmliefantennrDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmkundennrDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vminvnrDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vminvdateDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmorderreferenceDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmorderdateDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmsuborganisationDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmacctareaDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmlieferdatumDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmkopftextDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vminvtotalnetamounttextDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vminvtotalnetamountDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vminvtaxtextDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vminvtaxamountDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vminvtotalamounttextDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vminvtotalamountDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vminvcurrencyDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vminvduedateDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmktobanknameDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmktobicDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmktoibanDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmktoownerDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmktoreferenceDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vmfusstextDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn vminvtargetDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn kopfTextDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn fussTextDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn invVariantDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.DataGridViewTextBoxColumn displayNameDataGridViewTextBoxColumn;
        
        internal System.Windows.Forms.BindingSource invoiceViewModelBindingSource;
        
        internal System.Windows.Forms.BindingSource relatedDocBindingSource;
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        public ThisDocument(global::Microsoft.Office.Tools.Word.Factory factory, global::System.IServiceProvider serviceProvider) : 
                base(factory, serviceProvider, "ThisDocument", "ThisDocument") {
            Globals.Factory = factory;
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize() {
            base.Initialize();
            this.ThisApplication = this.GetHostItem<Microsoft.Office.Interop.Word.Application>(typeof(Microsoft.Office.Interop.Word.Application), "Application");
            Globals.ThisDocument = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
            this.InitializeCachedData();
            this.InitializeControls();
            this.InitializeComponents();
            this.InitializeData();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization() {
            this.InternalStartup();
            this.OnStartup();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings() {
            this.BeginInitialization();
            this.BindToData();
            this.EndInitialization();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData() {
            if ((this.DataHost == null)) {
                return;
            }
            if (this.DataHost.IsCacheInitialized) {
                this.DataHost.FillCachedData(this);
            }
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData() {
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName) {
            this.DataHost.StartCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName) {
            this.DataHost.StopCaching(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName) {
            return this.DataHost.IsCached(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization() {
            this.BeginInit();
            this.ActionsPane.BeginInit();
            this.b00.BeginInit();
            this.b01.BeginInit();
            this.b02.BeginInit();
            this.b03.BeginInit();
            this.b04.BeginInit();
            this.b05.BeginInit();
            this.b06.BeginInit();
            this.b07.BeginInit();
            this.b08.BeginInit();
            this.b09.BeginInit();
            this.b10.BeginInit();
            this.b11.BeginInit();
            this.b12.BeginInit();
            this.b13.BeginInit();
            this.b16.BeginInit();
            this.b17.BeginInit();
            this.b18.BeginInit();
            this.b19.BeginInit();
            this.b21.BeginInit();
            this.b22.BeginInit();
            this.b23.BeginInit();
            this.b24.BeginInit();
            this.bLiefNr.BeginInit();
            this.b26.BeginInit();
            this.b27.BeginInit();
            this.b28.BeginInit();
            this.CC_InvoiceDocType.BeginInit();
            this.CC_BillerName.BeginInit();
            this.CC_BillerStreet.BeginInit();
            this.CC_BillerPlz.BeginInit();
            this.CC_BillerTown.BeginInit();
            this.CC_BillerCountry.BeginInit();
            this.CC_BillerGln.BeginInit();
            this.CC_BillerContact.BeginInit();
            this.CC_BillerPhone.BeginInit();
            this.CC_BillerMail.BeginInit();
            this.CC_BillerVatID.BeginInit();
            this.CC_RecSalutation.BeginInit();
            this.CC_RecName.BeginInit();
            this.CC_RecStreet.BeginInit();
            this.CC_RecPlz.BeginInit();
            this.CC_RecTown.BeginInit();
            this.CC_RecCountry.BeginInit();
            this.CC_RecGln.BeginInit();
            this.CC_RecContact.BeginInit();
            this.CC_RecPhone.BeginInit();
            this.CC_RecMail.BeginInit();
            this.CC_RecVatID.BeginInit();
            this.CC_InTitle.BeginInit();
            this.CC_LiefantenNr.BeginInit();
            this.CC_KundenNr.BeginInit();
            this.CC_InvNr.BeginInit();
            this.CC_InvDate.BeginInit();
            this.CC_OrderReference.BeginInit();
            this.CC_OrderDate.BeginInit();
            this.CC_SubOrganisation.BeginInit();
            this.CC_AcctArea.BeginInit();
            this.CC_LieferDatum.BeginInit();
            this.CC_Kopftext.BeginInit();
            this.CC_InvTotalNetAmountText.BeginInit();
            this.CC_InvTotalNetAmount.BeginInit();
            this.CC_InvTaxText.BeginInit();
            this.CC_InvTaxAmount.BeginInit();
            this.CC_InvTotalAmountText.BeginInit();
            this.CC_InvTotalAmount.BeginInit();
            this.CC_InvCurrency.BeginInit();
            this.CC_InvDueDate.BeginInit();
            this.CC_KtoBankName.BeginInit();
            this.CC_KtoBic.BeginInit();
            this.CC_KtoIBAN.BeginInit();
            this.CC_KtoOwner.BeginInit();
            this.CC_KtoReference.BeginInit();
            this.CC_Fusstext.BeginInit();
            this.b98.BeginInit();
            this.b14.BeginInit();
            this.CC_DocComment.BeginInit();
            this.CC_DocRef.BeginInit();
            this.CC_RefType.BeginInit();
            this.CC_RefInvNr.BeginInit();
            this.CC_RefInvDate.BeginInit();
            this.CC_RefComment.BeginInit();
            this.CC_RefDocType.BeginInit();
            this.bEmpfMail.BeginInit();
            this.b30Formular.BeginInit();
            this.bkmkFormular.BeginInit();
            this.bHeadline.BeginInit();
            this.bestpos.BeginInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization() {
            this.bestpos.EndInit();
            this.bHeadline.EndInit();
            this.bkmkFormular.EndInit();
            this.b30Formular.EndInit();
            this.bEmpfMail.EndInit();
            this.CC_RefDocType.EndInit();
            this.CC_RefComment.EndInit();
            this.CC_RefInvDate.EndInit();
            this.CC_RefInvNr.EndInit();
            this.CC_RefType.EndInit();
            this.CC_DocRef.EndInit();
            this.CC_DocComment.EndInit();
            this.b14.EndInit();
            this.b98.EndInit();
            this.CC_Fusstext.EndInit();
            this.CC_KtoReference.EndInit();
            this.CC_KtoOwner.EndInit();
            this.CC_KtoIBAN.EndInit();
            this.CC_KtoBic.EndInit();
            this.CC_KtoBankName.EndInit();
            this.CC_InvDueDate.EndInit();
            this.CC_InvCurrency.EndInit();
            this.CC_InvTotalAmount.EndInit();
            this.CC_InvTotalAmountText.EndInit();
            this.CC_InvTaxAmount.EndInit();
            this.CC_InvTaxText.EndInit();
            this.CC_InvTotalNetAmount.EndInit();
            this.CC_InvTotalNetAmountText.EndInit();
            this.CC_Kopftext.EndInit();
            this.CC_LieferDatum.EndInit();
            this.CC_AcctArea.EndInit();
            this.CC_SubOrganisation.EndInit();
            this.CC_OrderDate.EndInit();
            this.CC_OrderReference.EndInit();
            this.CC_InvDate.EndInit();
            this.CC_InvNr.EndInit();
            this.CC_KundenNr.EndInit();
            this.CC_LiefantenNr.EndInit();
            this.CC_InTitle.EndInit();
            this.CC_RecVatID.EndInit();
            this.CC_RecMail.EndInit();
            this.CC_RecPhone.EndInit();
            this.CC_RecContact.EndInit();
            this.CC_RecGln.EndInit();
            this.CC_RecCountry.EndInit();
            this.CC_RecTown.EndInit();
            this.CC_RecPlz.EndInit();
            this.CC_RecStreet.EndInit();
            this.CC_RecName.EndInit();
            this.CC_RecSalutation.EndInit();
            this.CC_BillerVatID.EndInit();
            this.CC_BillerMail.EndInit();
            this.CC_BillerPhone.EndInit();
            this.CC_BillerContact.EndInit();
            this.CC_BillerGln.EndInit();
            this.CC_BillerCountry.EndInit();
            this.CC_BillerTown.EndInit();
            this.CC_BillerPlz.EndInit();
            this.CC_BillerStreet.EndInit();
            this.CC_BillerName.EndInit();
            this.CC_InvoiceDocType.EndInit();
            this.b28.EndInit();
            this.b27.EndInit();
            this.b26.EndInit();
            this.bLiefNr.EndInit();
            this.b24.EndInit();
            this.b23.EndInit();
            this.b22.EndInit();
            this.b21.EndInit();
            this.b19.EndInit();
            this.b18.EndInit();
            this.b17.EndInit();
            this.b16.EndInit();
            this.b13.EndInit();
            this.b12.EndInit();
            this.b11.EndInit();
            this.b10.EndInit();
            this.b09.EndInit();
            this.b08.EndInit();
            this.b07.EndInit();
            this.b06.EndInit();
            this.b05.EndInit();
            this.b04.EndInit();
            this.b03.EndInit();
            this.b02.EndInit();
            this.b01.EndInit();
            this.b00.EndInit();
            this.ActionsPane.EndInit();
            this.EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls() {
            this.ActionsPane = Globals.Factory.CreateActionsPane(null, null, "ActionsPane", "ActionsPane", this);
            this.b00 = Globals.Factory.CreateBookmark(null, null, "b00", "b00", this);
            this.b01 = Globals.Factory.CreateBookmark(null, null, "b01", "b01", this);
            this.b02 = Globals.Factory.CreateBookmark(null, null, "b02", "b02", this);
            this.b03 = Globals.Factory.CreateBookmark(null, null, "b03", "b03", this);
            this.b04 = Globals.Factory.CreateBookmark(null, null, "b04", "b04", this);
            this.b05 = Globals.Factory.CreateBookmark(null, null, "b05", "b05", this);
            this.b06 = Globals.Factory.CreateBookmark(null, null, "b06", "b06", this);
            this.b07 = Globals.Factory.CreateBookmark(null, null, "b07", "b07", this);
            this.b08 = Globals.Factory.CreateBookmark(null, null, "b08", "b08", this);
            this.b09 = Globals.Factory.CreateBookmark(null, null, "b09", "b09", this);
            this.b10 = Globals.Factory.CreateBookmark(null, null, "b10", "b10", this);
            this.b11 = Globals.Factory.CreateBookmark(null, null, "b11", "b11", this);
            this.b12 = Globals.Factory.CreateBookmark(null, null, "b12", "b12", this);
            this.b13 = Globals.Factory.CreateBookmark(null, null, "b13", "b13", this);
            this.b16 = Globals.Factory.CreateBookmark(null, null, "b16", "b16", this);
            this.b17 = Globals.Factory.CreateBookmark(null, null, "b17", "b17", this);
            this.b18 = Globals.Factory.CreateBookmark(null, null, "b18", "b18", this);
            this.b19 = Globals.Factory.CreateBookmark(null, null, "b19", "b19", this);
            this.b21 = Globals.Factory.CreateBookmark(null, null, "b21", "b21", this);
            this.b22 = Globals.Factory.CreateBookmark(null, null, "b22", "b22", this);
            this.b23 = Globals.Factory.CreateBookmark(null, null, "b23", "b23", this);
            this.b24 = Globals.Factory.CreateBookmark(null, null, "b24", "b24", this);
            this.bLiefNr = Globals.Factory.CreateBookmark(null, null, "bLiefNr", "bLiefNr", this);
            this.b26 = Globals.Factory.CreateBookmark(null, null, "b26", "b26", this);
            this.b27 = Globals.Factory.CreateBookmark(null, null, "b27", "b27", this);
            this.b28 = Globals.Factory.CreateBookmark(null, null, "b28", "b28", this);
            this.CC_InvoiceDocType = Globals.Factory.CreateDropDownListContentControl(null, null, "196466253", "CC_InvoiceDocType", this);
            this.CC_BillerName = Globals.Factory.CreatePlainTextContentControl(null, null, "79801737", "CC_BillerName", this);
            this.CC_BillerStreet = Globals.Factory.CreatePlainTextContentControl(null, null, "79801743", "CC_BillerStreet", this);
            this.CC_BillerPlz = Globals.Factory.CreatePlainTextContentControl(null, null, "79801754", "CC_BillerPlz", this);
            this.CC_BillerTown = Globals.Factory.CreatePlainTextContentControl(null, null, "79801761", "CC_BillerTown", this);
            this.CC_BillerCountry = Globals.Factory.CreateDropDownListContentControl(null, null, "79801769", "CC_BillerCountry", this);
            this.CC_BillerGln = Globals.Factory.CreatePlainTextContentControl(null, null, "79907892", "CC_BillerGln", this);
            this.CC_BillerContact = Globals.Factory.CreatePlainTextContentControl(null, null, "196466246", "CC_BillerContact", this);
            this.CC_BillerPhone = Globals.Factory.CreatePlainTextContentControl(null, null, "79801778", "CC_BillerPhone", this);
            this.CC_BillerMail = Globals.Factory.CreatePlainTextContentControl(null, null, "79801790", "CC_BillerMail", this);
            this.CC_BillerVatID = Globals.Factory.CreatePlainTextContentControl(null, null, "79801796", "CC_BillerVatID", this);
            this.CC_RecSalutation = Globals.Factory.CreatePlainTextContentControl(null, null, "79801823", "CC_RecSalutation", this);
            this.CC_RecName = Globals.Factory.CreatePlainTextContentControl(null, null, "79801802", "CC_RecName", this);
            this.CC_RecStreet = Globals.Factory.CreatePlainTextContentControl(null, null, "79801803", "CC_RecStreet", this);
            this.CC_RecPlz = Globals.Factory.CreatePlainTextContentControl(null, null, "79801804", "CC_RecPlz", this);
            this.CC_RecTown = Globals.Factory.CreatePlainTextContentControl(null, null, "79801805", "CC_RecTown", this);
            this.CC_RecCountry = Globals.Factory.CreateDropDownListContentControl(null, null, "79801806", "CC_RecCountry", this);
            this.CC_RecGln = Globals.Factory.CreatePlainTextContentControl(null, null, "79907893", "CC_RecGln", this);
            this.CC_RecContact = Globals.Factory.CreatePlainTextContentControl(null, null, "196466252", "CC_RecContact", this);
            this.CC_RecPhone = Globals.Factory.CreatePlainTextContentControl(null, null, "79801807", "CC_RecPhone", this);
            this.CC_RecMail = Globals.Factory.CreatePlainTextContentControl(null, null, "79801808", "CC_RecMail", this);
            this.CC_RecVatID = Globals.Factory.CreatePlainTextContentControl(null, null, "79801809", "CC_RecVatID", this);
            this.CC_InTitle = Globals.Factory.CreatePlainTextContentControl(null, null, "79801890", "CC_InTitle", this);
            this.CC_LiefantenNr = Globals.Factory.CreatePlainTextContentControl(null, null, "79907894", "CC_LiefantenNr", this);
            this.CC_KundenNr = Globals.Factory.CreatePlainTextContentControl(null, null, "79801899", "CC_KundenNr", this);
            this.CC_InvNr = Globals.Factory.CreatePlainTextContentControl(null, null, "79801908", "CC_InvNr", this);
            this.CC_InvDate = Globals.Factory.CreateDatePickerContentControl(null, null, "79801915", "CC_InvDate", this);
            this.CC_OrderReference = Globals.Factory.CreatePlainTextContentControl(null, null, "79802353", "CC_OrderReference", this);
            this.CC_OrderDate = Globals.Factory.CreateDatePickerContentControl(null, null, "79802359", "CC_OrderDate", this);
            this.CC_SubOrganisation = Globals.Factory.CreatePlainTextContentControl(null, null, "451220797", "CC_SubOrganisation", this);
            this.CC_AcctArea = Globals.Factory.CreatePlainTextContentControl(null, null, "448718423", "CC_AcctArea", this);
            this.CC_LieferDatum = Globals.Factory.CreateDatePickerContentControl(null, null, "79801974", "CC_LieferDatum", this);
            this.CC_Kopftext = Globals.Factory.CreatePlainTextContentControl(null, null, "79801934", "CC_Kopftext", this);
            this.CC_InvTotalNetAmountText = Globals.Factory.CreatePlainTextContentControl(null, null, "299064930", "CC_InvTotalNetAmountText", this);
            this.CC_InvTotalNetAmount = Globals.Factory.CreatePlainTextContentControl(null, null, "9791812", "CC_InvTotalNetAmount", this);
            this.CC_InvTaxText = Globals.Factory.CreatePlainTextContentControl(null, null, "299064926", "CC_InvTaxText", this);
            this.CC_InvTaxAmount = Globals.Factory.CreatePlainTextContentControl(null, null, "9791844", "CC_InvTaxAmount", this);
            this.CC_InvTotalAmountText = Globals.Factory.CreatePlainTextContentControl(null, null, "9791807", "CC_InvTotalAmountText", this);
            this.CC_InvTotalAmount = Globals.Factory.CreatePlainTextContentControl(null, null, "9791852", "CC_InvTotalAmount", this);
            this.CC_InvCurrency = Globals.Factory.CreateDropDownListContentControl(null, null, "79801943", "CC_InvCurrency", this);
            this.CC_InvDueDate = Globals.Factory.CreateDatePickerContentControl(null, null, "79801996", "CC_InvDueDate", this);
            this.CC_KtoBankName = Globals.Factory.CreatePlainTextContentControl(null, null, "79802057", "CC_KtoBankName", this);
            this.CC_KtoBic = Globals.Factory.CreatePlainTextContentControl(null, null, "1305064751", "CC_KtoBic", this);
            this.CC_KtoIBAN = Globals.Factory.CreatePlainTextContentControl(null, null, "79802182", "CC_KtoIBAN", this);
            this.CC_KtoOwner = Globals.Factory.CreatePlainTextContentControl(null, null, "79802069", "CC_KtoOwner", this);
            this.CC_KtoReference = Globals.Factory.CreatePlainTextContentControl(null, null, "8889965", "CC_KtoReference", this);
            this.CC_Fusstext = Globals.Factory.CreatePlainTextContentControl(null, null, "79801982", "CC_Fusstext", this);
            this.b98 = Globals.Factory.CreateBookmark(null, null, "b98", "b98", this);
            this.b14 = Globals.Factory.CreateBookmark(null, null, "b14", "b14", this);
            this.CC_DocComment = Globals.Factory.CreatePlainTextContentControl(null, null, "79903500", "CC_DocComment", this);
            this.CC_DocRef = Globals.Factory.CreatePlainTextContentControl(null, null, "79907141", "CC_DocRef", this);
            this.CC_RefType = Globals.Factory.CreateDropDownListContentControl(null, null, "1949436832", "CC_RefType", this);
            this.CC_RefInvNr = Globals.Factory.CreatePlainTextContentControl(null, null, "79909460", "CC_RefInvNr", this);
            this.CC_RefInvDate = Globals.Factory.CreateDatePickerContentControl(null, null, "79907088", "CC_RefInvDate", this);
            this.CC_RefComment = Globals.Factory.CreatePlainTextContentControl(null, null, "79904088", "CC_RefComment", this);
            this.CC_RefDocType = Globals.Factory.CreateDropDownListContentControl(null, null, "79901298", "CC_RefDocType", this);
            this.bEmpfMail = Globals.Factory.CreateBookmark(null, null, "bEmpfMail", "bEmpfMail", this);
            this.b30Formular = Globals.Factory.CreateBookmark(null, null, "b30Formular", "b30Formular", this);
            this.bkmkFormular = Globals.Factory.CreateBookmark(null, null, "bkmkFormular", "bkmkFormular", this);
            this.bHeadline = Globals.Factory.CreateBookmark(null, null, "bHeadline", "bHeadline", this);
            this.bestpos = Globals.Factory.CreateBookmark(null, null, "bestpos", "bestpos", this);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents() {
            this.components = new System.ComponentModel.Container();
            this.vmInvTypeDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmBillerNameDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmBillerStreetDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmBillerPlzDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmBillerTownDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmBillerCountryDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmBillerGlnDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmBillerContactDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmbillerphoneDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmbillermailDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmbillervatidDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmrecsalutationDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmrecnameDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmrecstreetDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmrecplzDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmrectownDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmreccountryDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmrecglnDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmreccontactDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmrecphoneDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmrecmailDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmrecvatidDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmintitleDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmliefantennrDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmkundennrDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vminvnrDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vminvdateDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmorderreferenceDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmorderdateDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmsuborganisationDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmacctareaDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmlieferdatumDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmkopftextDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vminvtotalnetamounttextDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vminvtotalnetamountDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vminvtaxtextDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vminvtaxamountDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vminvtotalamounttextDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vminvtotalamountDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vminvcurrencyDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vminvduedateDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmktobanknameDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmktobicDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmktoibanDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmktoownerDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmktoreferenceDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vmfusstextDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.vminvtargetDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.kopfTextDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.fussTextDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.invVariantDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.displayNameDataGridViewTextBoxColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.invoiceViewModelBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.relatedDocBindingSource = new System.Windows.Forms.BindingSource(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.invoiceViewModelBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.relatedDocBindingSource)).BeginInit();
            // 
            // ActionsPane
            // 
            this.ActionsPane.AutoSize = false;
            this.ActionsPane.AutoValidate = System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
            // 
            // b00
            // 
            this.b00.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b01
            // 
            this.b01.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b02
            // 
            this.b02.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b03
            // 
            this.b03.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b04
            // 
            this.b04.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b05
            // 
            this.b05.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b06
            // 
            this.b06.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b07
            // 
            this.b07.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b08
            // 
            this.b08.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b09
            // 
            this.b09.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b10
            // 
            this.b10.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b11
            // 
            this.b11.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b12
            // 
            this.b12.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b13
            // 
            this.b13.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b16
            // 
            this.b16.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b17
            // 
            this.b17.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b18
            // 
            this.b18.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b19
            // 
            this.b19.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b21
            // 
            this.b21.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b22
            // 
            this.b22.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b23
            // 
            this.b23.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b24
            // 
            this.b24.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // bLiefNr
            // 
            this.bLiefNr.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b26
            // 
            this.b26.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b27
            // 
            this.b27.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b28
            // 
            this.b28.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_InvoiceDocType
            // 
            this.CC_InvoiceDocType.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_BillerName
            // 
            this.CC_BillerName.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_BillerStreet
            // 
            this.CC_BillerStreet.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_BillerPlz
            // 
            this.CC_BillerPlz.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_BillerTown
            // 
            this.CC_BillerTown.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_BillerCountry
            // 
            this.CC_BillerCountry.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_BillerGln
            // 
            this.CC_BillerGln.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_BillerContact
            // 
            this.CC_BillerContact.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_BillerPhone
            // 
            this.CC_BillerPhone.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_BillerMail
            // 
            this.CC_BillerMail.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_BillerVatID
            // 
            this.CC_BillerVatID.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RecSalutation
            // 
            this.CC_RecSalutation.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RecName
            // 
            this.CC_RecName.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RecStreet
            // 
            this.CC_RecStreet.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RecPlz
            // 
            this.CC_RecPlz.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RecTown
            // 
            this.CC_RecTown.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RecCountry
            // 
            this.CC_RecCountry.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RecGln
            // 
            this.CC_RecGln.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RecContact
            // 
            this.CC_RecContact.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RecPhone
            // 
            this.CC_RecPhone.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RecMail
            // 
            this.CC_RecMail.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RecVatID
            // 
            this.CC_RecVatID.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_InTitle
            // 
            this.CC_InTitle.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_LiefantenNr
            // 
            this.CC_LiefantenNr.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_KundenNr
            // 
            this.CC_KundenNr.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_InvNr
            // 
            this.CC_InvNr.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_InvDate
            // 
            this.CC_InvDate.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_OrderReference
            // 
            this.CC_OrderReference.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_OrderDate
            // 
            this.CC_OrderDate.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_SubOrganisation
            // 
            this.CC_SubOrganisation.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_AcctArea
            // 
            this.CC_AcctArea.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_LieferDatum
            // 
            this.CC_LieferDatum.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_Kopftext
            // 
            this.CC_Kopftext.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_InvTotalNetAmountText
            // 
            this.CC_InvTotalNetAmountText.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_InvTotalNetAmount
            // 
            this.CC_InvTotalNetAmount.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_InvTaxText
            // 
            this.CC_InvTaxText.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_InvTaxAmount
            // 
            this.CC_InvTaxAmount.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_InvTotalAmountText
            // 
            this.CC_InvTotalAmountText.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_InvTotalAmount
            // 
            this.CC_InvTotalAmount.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_InvCurrency
            // 
            this.CC_InvCurrency.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_InvDueDate
            // 
            this.CC_InvDueDate.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_KtoBankName
            // 
            this.CC_KtoBankName.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_KtoBic
            // 
            this.CC_KtoBic.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_KtoIBAN
            // 
            this.CC_KtoIBAN.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_KtoOwner
            // 
            this.CC_KtoOwner.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_KtoReference
            // 
            this.CC_KtoReference.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_Fusstext
            // 
            this.CC_Fusstext.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b98
            // 
            this.b98.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b14
            // 
            this.b14.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_DocComment
            // 
            this.CC_DocComment.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_DocRef
            // 
            this.CC_DocRef.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RefType
            // 
            this.CC_RefType.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RefInvNr
            // 
            this.CC_RefInvNr.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RefInvDate
            // 
            this.CC_RefInvDate.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RefComment
            // 
            this.CC_RefComment.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // CC_RefDocType
            // 
            this.CC_RefDocType.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // bEmpfMail
            // 
            this.bEmpfMail.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // b30Formular
            // 
            this.b30Formular.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // bkmkFormular
            // 
            this.bkmkFormular.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // bHeadline
            // 
            this.bHeadline.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // bestpos
            // 
            this.bestpos.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.OnPropertyChanged;
            // 
            // vmInvTypeDataGridViewTextBoxColumn
            // 
            this.vmInvTypeDataGridViewTextBoxColumn.DataPropertyName = "VmInvType";
            this.vmInvTypeDataGridViewTextBoxColumn.HeaderText = "VmInvType";
            this.vmInvTypeDataGridViewTextBoxColumn.Name = "vmInvTypeDataGridViewTextBoxColumn";
            // 
            // vmBillerNameDataGridViewTextBoxColumn
            // 
            this.vmBillerNameDataGridViewTextBoxColumn.DataPropertyName = "VmBillerName";
            this.vmBillerNameDataGridViewTextBoxColumn.HeaderText = "VmBillerName";
            this.vmBillerNameDataGridViewTextBoxColumn.Name = "vmBillerNameDataGridViewTextBoxColumn";
            // 
            // vmBillerStreetDataGridViewTextBoxColumn
            // 
            this.vmBillerStreetDataGridViewTextBoxColumn.DataPropertyName = "VmBillerStreet";
            this.vmBillerStreetDataGridViewTextBoxColumn.HeaderText = "VmBillerStreet";
            this.vmBillerStreetDataGridViewTextBoxColumn.Name = "vmBillerStreetDataGridViewTextBoxColumn";
            // 
            // vmBillerPlzDataGridViewTextBoxColumn
            // 
            this.vmBillerPlzDataGridViewTextBoxColumn.DataPropertyName = "VmBillerPlz";
            this.vmBillerPlzDataGridViewTextBoxColumn.HeaderText = "VmBillerPlz";
            this.vmBillerPlzDataGridViewTextBoxColumn.Name = "vmBillerPlzDataGridViewTextBoxColumn";
            // 
            // vmBillerTownDataGridViewTextBoxColumn
            // 
            this.vmBillerTownDataGridViewTextBoxColumn.DataPropertyName = "VmBillerTown";
            this.vmBillerTownDataGridViewTextBoxColumn.HeaderText = "VmBillerTown";
            this.vmBillerTownDataGridViewTextBoxColumn.Name = "vmBillerTownDataGridViewTextBoxColumn";
            // 
            // vmBillerCountryDataGridViewTextBoxColumn
            // 
            this.vmBillerCountryDataGridViewTextBoxColumn.DataPropertyName = "VmBillerCountry";
            this.vmBillerCountryDataGridViewTextBoxColumn.HeaderText = "VmBillerCountry";
            this.vmBillerCountryDataGridViewTextBoxColumn.Name = "vmBillerCountryDataGridViewTextBoxColumn";
            // 
            // vmBillerGlnDataGridViewTextBoxColumn
            // 
            this.vmBillerGlnDataGridViewTextBoxColumn.DataPropertyName = "VmBillerGln";
            this.vmBillerGlnDataGridViewTextBoxColumn.HeaderText = "VmBillerGln";
            this.vmBillerGlnDataGridViewTextBoxColumn.Name = "vmBillerGlnDataGridViewTextBoxColumn";
            // 
            // vmBillerContactDataGridViewTextBoxColumn
            // 
            this.vmBillerContactDataGridViewTextBoxColumn.DataPropertyName = "VmBillerContact";
            this.vmBillerContactDataGridViewTextBoxColumn.HeaderText = "VmBillerContact";
            this.vmBillerContactDataGridViewTextBoxColumn.Name = "vmBillerContactDataGridViewTextBoxColumn";
            // 
            // vmbillerphoneDataGridViewTextBoxColumn
            // 
            this.vmbillerphoneDataGridViewTextBoxColumn.DataPropertyName = "Vmbillerphone";
            this.vmbillerphoneDataGridViewTextBoxColumn.HeaderText = "Vmbillerphone";
            this.vmbillerphoneDataGridViewTextBoxColumn.Name = "vmbillerphoneDataGridViewTextBoxColumn";
            // 
            // vmbillermailDataGridViewTextBoxColumn
            // 
            this.vmbillermailDataGridViewTextBoxColumn.DataPropertyName = "Vmbillermail";
            this.vmbillermailDataGridViewTextBoxColumn.HeaderText = "Vmbillermail";
            this.vmbillermailDataGridViewTextBoxColumn.Name = "vmbillermailDataGridViewTextBoxColumn";
            // 
            // vmbillervatidDataGridViewTextBoxColumn
            // 
            this.vmbillervatidDataGridViewTextBoxColumn.DataPropertyName = "Vmbillervatid";
            this.vmbillervatidDataGridViewTextBoxColumn.HeaderText = "Vmbillervatid";
            this.vmbillervatidDataGridViewTextBoxColumn.Name = "vmbillervatidDataGridViewTextBoxColumn";
            // 
            // vmrecsalutationDataGridViewTextBoxColumn
            // 
            this.vmrecsalutationDataGridViewTextBoxColumn.DataPropertyName = "Vmrecsalutation";
            this.vmrecsalutationDataGridViewTextBoxColumn.HeaderText = "Vmrecsalutation";
            this.vmrecsalutationDataGridViewTextBoxColumn.Name = "vmrecsalutationDataGridViewTextBoxColumn";
            // 
            // vmrecnameDataGridViewTextBoxColumn
            // 
            this.vmrecnameDataGridViewTextBoxColumn.DataPropertyName = "Vmrecname";
            this.vmrecnameDataGridViewTextBoxColumn.HeaderText = "Vmrecname";
            this.vmrecnameDataGridViewTextBoxColumn.Name = "vmrecnameDataGridViewTextBoxColumn";
            // 
            // vmrecstreetDataGridViewTextBoxColumn
            // 
            this.vmrecstreetDataGridViewTextBoxColumn.DataPropertyName = "Vmrecstreet";
            this.vmrecstreetDataGridViewTextBoxColumn.HeaderText = "Vmrecstreet";
            this.vmrecstreetDataGridViewTextBoxColumn.Name = "vmrecstreetDataGridViewTextBoxColumn";
            // 
            // vmrecplzDataGridViewTextBoxColumn
            // 
            this.vmrecplzDataGridViewTextBoxColumn.DataPropertyName = "Vmrecplz";
            this.vmrecplzDataGridViewTextBoxColumn.HeaderText = "Vmrecplz";
            this.vmrecplzDataGridViewTextBoxColumn.Name = "vmrecplzDataGridViewTextBoxColumn";
            // 
            // vmrectownDataGridViewTextBoxColumn
            // 
            this.vmrectownDataGridViewTextBoxColumn.DataPropertyName = "Vmrectown";
            this.vmrectownDataGridViewTextBoxColumn.HeaderText = "Vmrectown";
            this.vmrectownDataGridViewTextBoxColumn.Name = "vmrectownDataGridViewTextBoxColumn";
            // 
            // vmreccountryDataGridViewTextBoxColumn
            // 
            this.vmreccountryDataGridViewTextBoxColumn.DataPropertyName = "Vmreccountry";
            this.vmreccountryDataGridViewTextBoxColumn.HeaderText = "Vmreccountry";
            this.vmreccountryDataGridViewTextBoxColumn.Name = "vmreccountryDataGridViewTextBoxColumn";
            // 
            // vmrecglnDataGridViewTextBoxColumn
            // 
            this.vmrecglnDataGridViewTextBoxColumn.DataPropertyName = "Vmrecgln";
            this.vmrecglnDataGridViewTextBoxColumn.HeaderText = "Vmrecgln";
            this.vmrecglnDataGridViewTextBoxColumn.Name = "vmrecglnDataGridViewTextBoxColumn";
            // 
            // vmreccontactDataGridViewTextBoxColumn
            // 
            this.vmreccontactDataGridViewTextBoxColumn.DataPropertyName = "Vmreccontact";
            this.vmreccontactDataGridViewTextBoxColumn.HeaderText = "Vmreccontact";
            this.vmreccontactDataGridViewTextBoxColumn.Name = "vmreccontactDataGridViewTextBoxColumn";
            // 
            // vmrecphoneDataGridViewTextBoxColumn
            // 
            this.vmrecphoneDataGridViewTextBoxColumn.DataPropertyName = "Vmrecphone";
            this.vmrecphoneDataGridViewTextBoxColumn.HeaderText = "Vmrecphone";
            this.vmrecphoneDataGridViewTextBoxColumn.Name = "vmrecphoneDataGridViewTextBoxColumn";
            // 
            // vmrecmailDataGridViewTextBoxColumn
            // 
            this.vmrecmailDataGridViewTextBoxColumn.DataPropertyName = "Vmrecmail";
            this.vmrecmailDataGridViewTextBoxColumn.HeaderText = "Vmrecmail";
            this.vmrecmailDataGridViewTextBoxColumn.Name = "vmrecmailDataGridViewTextBoxColumn";
            // 
            // vmrecvatidDataGridViewTextBoxColumn
            // 
            this.vmrecvatidDataGridViewTextBoxColumn.DataPropertyName = "Vmrecvatid";
            this.vmrecvatidDataGridViewTextBoxColumn.HeaderText = "Vmrecvatid";
            this.vmrecvatidDataGridViewTextBoxColumn.Name = "vmrecvatidDataGridViewTextBoxColumn";
            // 
            // vmintitleDataGridViewTextBoxColumn
            // 
            this.vmintitleDataGridViewTextBoxColumn.DataPropertyName = "Vmintitle";
            this.vmintitleDataGridViewTextBoxColumn.HeaderText = "Vmintitle";
            this.vmintitleDataGridViewTextBoxColumn.Name = "vmintitleDataGridViewTextBoxColumn";
            // 
            // vmliefantennrDataGridViewTextBoxColumn
            // 
            this.vmliefantennrDataGridViewTextBoxColumn.DataPropertyName = "Vmliefantennr";
            this.vmliefantennrDataGridViewTextBoxColumn.HeaderText = "Vmliefantennr";
            this.vmliefantennrDataGridViewTextBoxColumn.Name = "vmliefantennrDataGridViewTextBoxColumn";
            // 
            // vmkundennrDataGridViewTextBoxColumn
            // 
            this.vmkundennrDataGridViewTextBoxColumn.DataPropertyName = "Vmkundennr";
            this.vmkundennrDataGridViewTextBoxColumn.HeaderText = "Vmkundennr";
            this.vmkundennrDataGridViewTextBoxColumn.Name = "vmkundennrDataGridViewTextBoxColumn";
            // 
            // vminvnrDataGridViewTextBoxColumn
            // 
            this.vminvnrDataGridViewTextBoxColumn.DataPropertyName = "Vminvnr";
            this.vminvnrDataGridViewTextBoxColumn.HeaderText = "Vminvnr";
            this.vminvnrDataGridViewTextBoxColumn.Name = "vminvnrDataGridViewTextBoxColumn";
            // 
            // vminvdateDataGridViewTextBoxColumn
            // 
            this.vminvdateDataGridViewTextBoxColumn.DataPropertyName = "Vminvdate";
            this.vminvdateDataGridViewTextBoxColumn.HeaderText = "Vminvdate";
            this.vminvdateDataGridViewTextBoxColumn.Name = "vminvdateDataGridViewTextBoxColumn";
            // 
            // vmorderreferenceDataGridViewTextBoxColumn
            // 
            this.vmorderreferenceDataGridViewTextBoxColumn.DataPropertyName = "Vmorderreference";
            this.vmorderreferenceDataGridViewTextBoxColumn.HeaderText = "Vmorderreference";
            this.vmorderreferenceDataGridViewTextBoxColumn.Name = "vmorderreferenceDataGridViewTextBoxColumn";
            // 
            // vmorderdateDataGridViewTextBoxColumn
            // 
            this.vmorderdateDataGridViewTextBoxColumn.DataPropertyName = "Vmorderdate";
            this.vmorderdateDataGridViewTextBoxColumn.HeaderText = "Vmorderdate";
            this.vmorderdateDataGridViewTextBoxColumn.Name = "vmorderdateDataGridViewTextBoxColumn";
            // 
            // vmsuborganisationDataGridViewTextBoxColumn
            // 
            this.vmsuborganisationDataGridViewTextBoxColumn.DataPropertyName = "Vmsuborganisation";
            this.vmsuborganisationDataGridViewTextBoxColumn.HeaderText = "Vmsuborganisation";
            this.vmsuborganisationDataGridViewTextBoxColumn.Name = "vmsuborganisationDataGridViewTextBoxColumn";
            // 
            // vmacctareaDataGridViewTextBoxColumn
            // 
            this.vmacctareaDataGridViewTextBoxColumn.DataPropertyName = "Vmacctarea";
            this.vmacctareaDataGridViewTextBoxColumn.HeaderText = "Vmacctarea";
            this.vmacctareaDataGridViewTextBoxColumn.Name = "vmacctareaDataGridViewTextBoxColumn";
            // 
            // vmlieferdatumDataGridViewTextBoxColumn
            // 
            this.vmlieferdatumDataGridViewTextBoxColumn.DataPropertyName = "Vmlieferdatum";
            this.vmlieferdatumDataGridViewTextBoxColumn.HeaderText = "Vmlieferdatum";
            this.vmlieferdatumDataGridViewTextBoxColumn.Name = "vmlieferdatumDataGridViewTextBoxColumn";
            // 
            // vmkopftextDataGridViewTextBoxColumn
            // 
            this.vmkopftextDataGridViewTextBoxColumn.DataPropertyName = "Vmkopftext";
            this.vmkopftextDataGridViewTextBoxColumn.HeaderText = "Vmkopftext";
            this.vmkopftextDataGridViewTextBoxColumn.Name = "vmkopftextDataGridViewTextBoxColumn";
            // 
            // vminvtotalnetamounttextDataGridViewTextBoxColumn
            // 
            this.vminvtotalnetamounttextDataGridViewTextBoxColumn.DataPropertyName = "Vminvtotalnetamounttext";
            this.vminvtotalnetamounttextDataGridViewTextBoxColumn.HeaderText = "Vminvtotalnetamounttext";
            this.vminvtotalnetamounttextDataGridViewTextBoxColumn.Name = "vminvtotalnetamounttextDataGridViewTextBoxColumn";
            // 
            // vminvtotalnetamountDataGridViewTextBoxColumn
            // 
            this.vminvtotalnetamountDataGridViewTextBoxColumn.DataPropertyName = "Vminvtotalnetamount";
            this.vminvtotalnetamountDataGridViewTextBoxColumn.HeaderText = "Vminvtotalnetamount";
            this.vminvtotalnetamountDataGridViewTextBoxColumn.Name = "vminvtotalnetamountDataGridViewTextBoxColumn";
            // 
            // vminvtaxtextDataGridViewTextBoxColumn
            // 
            this.vminvtaxtextDataGridViewTextBoxColumn.DataPropertyName = "Vminvtaxtext";
            this.vminvtaxtextDataGridViewTextBoxColumn.HeaderText = "Vminvtaxtext";
            this.vminvtaxtextDataGridViewTextBoxColumn.Name = "vminvtaxtextDataGridViewTextBoxColumn";
            // 
            // vminvtaxamountDataGridViewTextBoxColumn
            // 
            this.vminvtaxamountDataGridViewTextBoxColumn.DataPropertyName = "Vminvtaxamount";
            this.vminvtaxamountDataGridViewTextBoxColumn.HeaderText = "Vminvtaxamount";
            this.vminvtaxamountDataGridViewTextBoxColumn.Name = "vminvtaxamountDataGridViewTextBoxColumn";
            // 
            // vminvtotalamounttextDataGridViewTextBoxColumn
            // 
            this.vminvtotalamounttextDataGridViewTextBoxColumn.DataPropertyName = "Vminvtotalamounttext";
            this.vminvtotalamounttextDataGridViewTextBoxColumn.HeaderText = "Vminvtotalamounttext";
            this.vminvtotalamounttextDataGridViewTextBoxColumn.Name = "vminvtotalamounttextDataGridViewTextBoxColumn";
            // 
            // vminvtotalamountDataGridViewTextBoxColumn
            // 
            this.vminvtotalamountDataGridViewTextBoxColumn.DataPropertyName = "Vminvtotalamount";
            this.vminvtotalamountDataGridViewTextBoxColumn.HeaderText = "Vminvtotalamount";
            this.vminvtotalamountDataGridViewTextBoxColumn.Name = "vminvtotalamountDataGridViewTextBoxColumn";
            // 
            // vminvcurrencyDataGridViewTextBoxColumn
            // 
            this.vminvcurrencyDataGridViewTextBoxColumn.DataPropertyName = "Vminvcurrency";
            this.vminvcurrencyDataGridViewTextBoxColumn.HeaderText = "Vminvcurrency";
            this.vminvcurrencyDataGridViewTextBoxColumn.Name = "vminvcurrencyDataGridViewTextBoxColumn";
            // 
            // vminvduedateDataGridViewTextBoxColumn
            // 
            this.vminvduedateDataGridViewTextBoxColumn.DataPropertyName = "Vminvduedate";
            this.vminvduedateDataGridViewTextBoxColumn.HeaderText = "Vminvduedate";
            this.vminvduedateDataGridViewTextBoxColumn.Name = "vminvduedateDataGridViewTextBoxColumn";
            // 
            // vmktobanknameDataGridViewTextBoxColumn
            // 
            this.vmktobanknameDataGridViewTextBoxColumn.DataPropertyName = "Vmktobankname";
            this.vmktobanknameDataGridViewTextBoxColumn.HeaderText = "Vmktobankname";
            this.vmktobanknameDataGridViewTextBoxColumn.Name = "vmktobanknameDataGridViewTextBoxColumn";
            // 
            // vmktobicDataGridViewTextBoxColumn
            // 
            this.vmktobicDataGridViewTextBoxColumn.DataPropertyName = "Vmktobic";
            this.vmktobicDataGridViewTextBoxColumn.HeaderText = "Vmktobic";
            this.vmktobicDataGridViewTextBoxColumn.Name = "vmktobicDataGridViewTextBoxColumn";
            // 
            // vmktoibanDataGridViewTextBoxColumn
            // 
            this.vmktoibanDataGridViewTextBoxColumn.DataPropertyName = "Vmktoiban";
            this.vmktoibanDataGridViewTextBoxColumn.HeaderText = "Vmktoiban";
            this.vmktoibanDataGridViewTextBoxColumn.Name = "vmktoibanDataGridViewTextBoxColumn";
            // 
            // vmktoownerDataGridViewTextBoxColumn
            // 
            this.vmktoownerDataGridViewTextBoxColumn.DataPropertyName = "Vmktoowner";
            this.vmktoownerDataGridViewTextBoxColumn.HeaderText = "Vmktoowner";
            this.vmktoownerDataGridViewTextBoxColumn.Name = "vmktoownerDataGridViewTextBoxColumn";
            // 
            // vmktoreferenceDataGridViewTextBoxColumn
            // 
            this.vmktoreferenceDataGridViewTextBoxColumn.DataPropertyName = "Vmktoreference";
            this.vmktoreferenceDataGridViewTextBoxColumn.HeaderText = "Vmktoreference";
            this.vmktoreferenceDataGridViewTextBoxColumn.Name = "vmktoreferenceDataGridViewTextBoxColumn";
            // 
            // vmfusstextDataGridViewTextBoxColumn
            // 
            this.vmfusstextDataGridViewTextBoxColumn.DataPropertyName = "Vmfusstext";
            this.vmfusstextDataGridViewTextBoxColumn.HeaderText = "Vmfusstext";
            this.vmfusstextDataGridViewTextBoxColumn.Name = "vmfusstextDataGridViewTextBoxColumn";
            // 
            // vminvtargetDataGridViewTextBoxColumn
            // 
            this.vminvtargetDataGridViewTextBoxColumn.DataPropertyName = "Vminvtarget";
            this.vminvtargetDataGridViewTextBoxColumn.HeaderText = "Vminvtarget";
            this.vminvtargetDataGridViewTextBoxColumn.Name = "vminvtargetDataGridViewTextBoxColumn";
            // 
            // kopfTextDataGridViewTextBoxColumn
            // 
            this.kopfTextDataGridViewTextBoxColumn.DataPropertyName = "KopfText";
            this.kopfTextDataGridViewTextBoxColumn.HeaderText = "KopfText";
            this.kopfTextDataGridViewTextBoxColumn.Name = "kopfTextDataGridViewTextBoxColumn";
            // 
            // fussTextDataGridViewTextBoxColumn
            // 
            this.fussTextDataGridViewTextBoxColumn.DataPropertyName = "FussText";
            this.fussTextDataGridViewTextBoxColumn.HeaderText = "FussText";
            this.fussTextDataGridViewTextBoxColumn.Name = "fussTextDataGridViewTextBoxColumn";
            // 
            // invVariantDataGridViewTextBoxColumn
            // 
            this.invVariantDataGridViewTextBoxColumn.DataPropertyName = "InvVariant";
            this.invVariantDataGridViewTextBoxColumn.HeaderText = "InvVariant";
            this.invVariantDataGridViewTextBoxColumn.Name = "invVariantDataGridViewTextBoxColumn";
            // 
            // displayNameDataGridViewTextBoxColumn
            // 
            this.displayNameDataGridViewTextBoxColumn.DataPropertyName = "DisplayName";
            this.displayNameDataGridViewTextBoxColumn.HeaderText = "DisplayName";
            this.displayNameDataGridViewTextBoxColumn.Name = "displayNameDataGridViewTextBoxColumn";
            this.displayNameDataGridViewTextBoxColumn.ReadOnly = true;
            // 
            // relatedDocBindingSource
            // 
            this.relatedDocBindingSource.DataSource = typeof(ebIViewModels.ViewModels.RelatedDocumentViewModel);
            // 
            // ThisDocument
            // 
            ((System.ComponentModel.ISupportInitialize)(this.invoiceViewModelBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.relatedDocBindingSource)).EndInit();
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName) {
            return this.DataHost.NeedsFill(this, MemberName);
        }
        
        /// 
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown() {
            this.bestpos.Dispose();
            this.bHeadline.Dispose();
            this.bkmkFormular.Dispose();
            this.b30Formular.Dispose();
            this.bEmpfMail.Dispose();
            this.CC_RefDocType.Dispose();
            this.CC_RefComment.Dispose();
            this.CC_RefInvDate.Dispose();
            this.CC_RefInvNr.Dispose();
            this.CC_RefType.Dispose();
            this.CC_DocRef.Dispose();
            this.CC_DocComment.Dispose();
            this.b14.Dispose();
            this.b98.Dispose();
            this.CC_Fusstext.Dispose();
            this.CC_KtoReference.Dispose();
            this.CC_KtoOwner.Dispose();
            this.CC_KtoIBAN.Dispose();
            this.CC_KtoBic.Dispose();
            this.CC_KtoBankName.Dispose();
            this.CC_InvDueDate.Dispose();
            this.CC_InvCurrency.Dispose();
            this.CC_InvTotalAmount.Dispose();
            this.CC_InvTotalAmountText.Dispose();
            this.CC_InvTaxAmount.Dispose();
            this.CC_InvTaxText.Dispose();
            this.CC_InvTotalNetAmount.Dispose();
            this.CC_InvTotalNetAmountText.Dispose();
            this.CC_Kopftext.Dispose();
            this.CC_LieferDatum.Dispose();
            this.CC_AcctArea.Dispose();
            this.CC_SubOrganisation.Dispose();
            this.CC_OrderDate.Dispose();
            this.CC_OrderReference.Dispose();
            this.CC_InvDate.Dispose();
            this.CC_InvNr.Dispose();
            this.CC_KundenNr.Dispose();
            this.CC_LiefantenNr.Dispose();
            this.CC_InTitle.Dispose();
            this.CC_RecVatID.Dispose();
            this.CC_RecMail.Dispose();
            this.CC_RecPhone.Dispose();
            this.CC_RecContact.Dispose();
            this.CC_RecGln.Dispose();
            this.CC_RecCountry.Dispose();
            this.CC_RecTown.Dispose();
            this.CC_RecPlz.Dispose();
            this.CC_RecStreet.Dispose();
            this.CC_RecName.Dispose();
            this.CC_RecSalutation.Dispose();
            this.CC_BillerVatID.Dispose();
            this.CC_BillerMail.Dispose();
            this.CC_BillerPhone.Dispose();
            this.CC_BillerContact.Dispose();
            this.CC_BillerGln.Dispose();
            this.CC_BillerCountry.Dispose();
            this.CC_BillerTown.Dispose();
            this.CC_BillerPlz.Dispose();
            this.CC_BillerStreet.Dispose();
            this.CC_BillerName.Dispose();
            this.CC_InvoiceDocType.Dispose();
            this.b28.Dispose();
            this.b27.Dispose();
            this.b26.Dispose();
            this.bLiefNr.Dispose();
            this.b24.Dispose();
            this.b23.Dispose();
            this.b22.Dispose();
            this.b21.Dispose();
            this.b19.Dispose();
            this.b18.Dispose();
            this.b17.Dispose();
            this.b16.Dispose();
            this.b13.Dispose();
            this.b12.Dispose();
            this.b11.Dispose();
            this.b10.Dispose();
            this.b09.Dispose();
            this.b08.Dispose();
            this.b07.Dispose();
            this.b06.Dispose();
            this.b05.Dispose();
            this.b04.Dispose();
            this.b03.Dispose();
            this.b02.Dispose();
            this.b01.Dispose();
            this.b00.Dispose();
            this.ActionsPane.Dispose();
            base.OnShutdown();
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
    internal sealed partial class Globals {
        
        /// 
        private Globals() {
        }
        
        private static ThisDocument _ThisDocument;
        
        private static global::Microsoft.Office.Tools.Word.Factory _factory;
        
        private static ThisRibbonCollection _ThisRibbonCollection;
        
        internal static ThisDocument ThisDocument {
            get {
                return _ThisDocument;
            }
            set {
                if ((_ThisDocument == null)) {
                    _ThisDocument = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static global::Microsoft.Office.Tools.Word.Factory Factory {
            get {
                return _factory;
            }
            set {
                if ((_factory == null)) {
                    _factory = value;
                }
                else {
                    throw new System.NotSupportedException();
                }
            }
        }
        
        internal static ThisRibbonCollection Ribbons {
            get {
                if ((_ThisRibbonCollection == null)) {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }
    }
    
    /// 
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase {
        
        /// 
        internal ThisRibbonCollection(global::Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : 
                base(factory) {
        }
    }
}
