//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SettingsManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetName {
            get {
                return ((string)(this["SetName"]));
            }
            set {
                this["SetName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetStrasse {
            get {
                return ((string)(this["SetStrasse"]));
            }
            set {
                this["SetStrasse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetPLZ {
            get {
                return ((string)(this["SetPLZ"]));
            }
            set {
                this["SetPLZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetOrt {
            get {
                return ((string)(this["SetOrt"]));
            }
            set {
                this["SetOrt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetTelNr {
            get {
                return ((string)(this["SetTelNr"]));
            }
            set {
                this["SetTelNr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetEmail {
            get {
                return ((string)(this["SetEmail"]));
            }
            set {
                this["SetEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetVATID {
            get {
                return ((string)(this["SetVATID"]));
            }
            set {
                this["SetVATID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AT")]
        public string SetLand {
            get {
                return ((string)(this["SetLand"]));
            }
            set {
                this["SetLand"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetBank {
            get {
                return ((string)(this["SetBank"]));
            }
            set {
                this["SetBank"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetKontowortlaut {
            get {
                return ((string)(this["SetKontowortlaut"]));
            }
            set {
                this["SetKontowortlaut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetIBAN {
            get {
                return ((string)(this["SetIBAN"]));
            }
            set {
                this["SetIBAN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EUR")]
        public string SetWhrg {
            get {
                return ((string)(this["SetWhrg"]));
            }
            set {
                this["SetWhrg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetBillerContact {
            get {
                return ((string)(this["SetBillerContact"]));
            }
            set {
                this["SetBillerContact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetMwStTab {
            get {
                return ((string)(this["SetMwStTab"]));
            }
            set {
                this["SetMwStTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public decimal SetMwStDefault {
            get {
                return ((decimal)(this["SetMwStDefault"]));
            }
            set {
                this["SetMwStDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetHandyNr {
            get {
                return ((string)(this["SetHandyNr"]));
            }
            set {
                this["SetHandyNr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetBetreff {
            get {
                return ((string)(this["SetBetreff"]));
            }
            set {
                this["SetBetreff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetMailText {
            get {
                return ((string)(this["SetMailText"]));
            }
            set {
                this["SetMailText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetSendEtresor {
            get {
                return ((bool)(this["SetSendEtresor"]));
            }
            set {
                this["SetSendEtresor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetEtresorMail {
            get {
                return ((string)(this["SetEtresorMail"]));
            }
            set {
                this["SetEtresorMail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SetSaveLocal {
            get {
                return ((bool)(this["SetSaveLocal"]));
            }
            set {
                this["SetSaveLocal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetLocalPath {
            get {
                return ((string)(this["SetLocalPath"]));
            }
            set {
                this["SetLocalPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetTemplatePath {
            get {
                return ((string)(this["SetTemplatePath"]));
            }
            set {
                this["SetTemplatePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetLocalPathSigned {
            get {
                return ((string)(this["SetLocalPathSigned"]));
            }
            set {
                this["SetLocalPathSigned"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetBIC {
            get {
                return ((string)(this["SetBIC"]));
            }
            set {
                this["SetBIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetVorwahl {
            get {
                return ((string)(this["SetVorwahl"]));
            }
            set {
                this["SetVorwahl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetTeilnehmer {
            get {
                return ((string)(this["SetTeilnehmer"]));
            }
            set {
                this["SetTeilnehmer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetBenutzer {
            get {
                return ((string)(this["SetBenutzer"]));
            }
            set {
                this["SetBenutzer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SetVStBerechtigt {
            get {
                return ((bool)(this["SetVStBerechtigt"]));
            }
            set {
                this["SetVStBerechtigt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetVStText {
            get {
                return ((string)(this["SetVStText"]));
            }
            set {
                this["SetVStText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"
              Sehr geehrte(r) Kunde,

              beigefügt erhalten Sie die Rechnung Nr. [RECHNUNGSNR] vom [RECHNUNGSDATUM] mit dem Ersuchen um termingerechte Erledigung.

              Mit freundlichen Grüßen Ihr

              [RECHNUNGSSTELLER]
              Kontakt: [KONTAKT]
              Telefon: [TELEFON]
              E-Mail: [EMAIL]
            ")]
        public string DefaultMailBody {
            get {
                return ((string)(this["DefaultMailBody"]));
            }
            set {
                this["DefaultMailBody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rechnung Nr. [RECHNUNGSNR] vom [RECHNUNGSDATUM] ")]
        public string DefaultMailSubject {
            get {
                return ((string)(this["DefaultMailSubject"]));
            }
            set {
                this["DefaultMailSubject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SetSignType {
            get {
                return ((int)(this["SetSignType"]));
            }
            set {
                this["SetSignType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetMyGLN {
            get {
                return ((string)(this["SetMyGLN"]));
            }
            set {
                this["SetMyGLN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetUnitOfMeasure {
            get {
                return ((string)(this["SetUnitOfMeasure"]));
            }
            set {
                this["SetUnitOfMeasure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NAR")]
        public string SetUoMDefault {
            get {
                return ((string)(this["SetUoMDefault"]));
            }
            set {
                this["SetUoMDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SetZustellExe {
            get {
                return ((string)(this["SetZustellExe"]));
            }
            set {
                this["SetZustellExe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{0} {1} {2}")]
        public string SetZustellParm {
            get {
                return ((string)(this["SetZustellParm"]));
            }
            set {
                this["SetZustellParm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setZustellWorkDir {
            get {
                return ((string)(this["setZustellWorkDir"]));
            }
            set {
                this["setZustellWorkDir"] = value;
            }
        }
    }
}
