//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Dieser Quellcode wurde automatisch generiert von xsd, Version=4.6.1055.0.
// 
namespace ebIModels.Schema.ebInterface5p0 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Invoice", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class InvoiceType {
        
        private string invoiceNumberField;
        
        private System.DateTime invoiceDateField;
        
        private CancelledOriginalDocumentType cancelledOriginalDocumentField;
        
        private RelatedDocumentType[] relatedDocumentField;
        
        private AdditionalInformationType[] additionalInformationField;
        
        private DeliveryType deliveryField;
        
        private BillerType billerField;
        
        private InvoiceRecipientType invoiceRecipientField;
        
        private OrderingPartyType orderingPartyField;
        
        private DetailsType detailsField;
        
        private ReductionAndSurchargeDetailsType reductionAndSurchargeDetailsField;
        
        private TaxType taxField;
        
        private decimal totalGrossAmountField;
        
        private decimal prepaidAmountField;
        
        private bool prepaidAmountFieldSpecified;
        
        private decimal roundingAmountField;
        
        private bool roundingAmountFieldSpecified;
        
        private decimal payableAmountField;
        
        private PaymentMethodType paymentMethodField;
        
        private PaymentConditionsType paymentConditionsField;
        
        private string commentField;
        
        private string generatingSystemField;
        
        private DocumentTypeType documentTypeField;
        
        private string invoiceCurrencyField;
        
        private bool manualProcessingField;
        
        private bool manualProcessingFieldSpecified;
        
        private string documentTitleField;
        
        private string languageField;
        
        private bool isDuplicateField;
        
        private bool isDuplicateFieldSpecified;
        
        /// <remarks/>
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        public CancelledOriginalDocumentType CancelledOriginalDocument {
            get {
                return this.cancelledOriginalDocumentField;
            }
            set {
                this.cancelledOriginalDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("RelatedDocument")]
        public RelatedDocumentType[] RelatedDocument {
            get {
                return this.relatedDocumentField;
            }
            set {
                this.relatedDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalInformation")]
        public AdditionalInformationType[] AdditionalInformation {
            get {
                return this.additionalInformationField;
            }
            set {
                this.additionalInformationField = value;
            }
        }
        
        /// <remarks/>
        public DeliveryType Delivery {
            get {
                return this.deliveryField;
            }
            set {
                this.deliveryField = value;
            }
        }
        
        /// <remarks/>
        public BillerType Biller {
            get {
                return this.billerField;
            }
            set {
                this.billerField = value;
            }
        }
        
        /// <remarks/>
        public InvoiceRecipientType InvoiceRecipient {
            get {
                return this.invoiceRecipientField;
            }
            set {
                this.invoiceRecipientField = value;
            }
        }
        
        /// <remarks/>
        public OrderingPartyType OrderingParty {
            get {
                return this.orderingPartyField;
            }
            set {
                this.orderingPartyField = value;
            }
        }
        
        /// <remarks/>
        public DetailsType Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
            }
        }
        
        /// <remarks/>
        public ReductionAndSurchargeDetailsType ReductionAndSurchargeDetails {
            get {
                return this.reductionAndSurchargeDetailsField;
            }
            set {
                this.reductionAndSurchargeDetailsField = value;
            }
        }
        
        /// <remarks/>
        public TaxType Tax {
            get {
                return this.taxField;
            }
            set {
                this.taxField = value;
            }
        }
        
        /// <remarks/>
        public decimal TotalGrossAmount {
            get {
                return this.totalGrossAmountField;
            }
            set {
                this.totalGrossAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal PrepaidAmount {
            get {
                return this.prepaidAmountField;
            }
            set {
                this.prepaidAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrepaidAmountSpecified {
            get {
                return this.prepaidAmountFieldSpecified;
            }
            set {
                this.prepaidAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal RoundingAmount {
            get {
                return this.roundingAmountField;
            }
            set {
                this.roundingAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RoundingAmountSpecified {
            get {
                return this.roundingAmountFieldSpecified;
            }
            set {
                this.roundingAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal PayableAmount {
            get {
                return this.payableAmountField;
            }
            set {
                this.payableAmountField = value;
            }
        }
        
        /// <remarks/>
        public PaymentMethodType PaymentMethod {
            get {
                return this.paymentMethodField;
            }
            set {
                this.paymentMethodField = value;
            }
        }
        
        /// <remarks/>
        public PaymentConditionsType PaymentConditions {
            get {
                return this.paymentConditionsField;
            }
            set {
                this.paymentConditionsField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string GeneratingSystem {
            get {
                return this.generatingSystemField;
            }
            set {
                this.generatingSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public DocumentTypeType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token")]
        public string InvoiceCurrency {
            get {
                return this.invoiceCurrencyField;
            }
            set {
                this.invoiceCurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool ManualProcessing {
            get {
                return this.manualProcessingField;
            }
            set {
                this.manualProcessingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ManualProcessingSpecified {
            get {
                return this.manualProcessingFieldSpecified;
            }
            set {
                this.manualProcessingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string DocumentTitle {
            get {
                return this.documentTitleField;
            }
            set {
                this.documentTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool IsDuplicate {
            get {
                return this.isDuplicateField;
            }
            set {
                this.isDuplicateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDuplicateSpecified {
            get {
                return this.isDuplicateFieldSpecified;
            }
            set {
                this.isDuplicateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("CancelledOriginalDocument", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class CancelledOriginalDocumentType {
        
        private string invoiceNumberField;
        
        private System.DateTime invoiceDateField;
        
        private DocumentTypeType documentTypeField;
        
        private bool documentTypeFieldSpecified;
        
        private string commentField;
        
        /// <remarks/>
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        public DocumentTypeType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentTypeSpecified {
            get {
                return this.documentTypeFieldSpecified;
            }
            set {
                this.documentTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("DocumentType", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public enum DocumentTypeType {
        
        /// <remarks/>
        CreditMemo,
        
        /// <remarks/>
        FinalSettlement,
        
        /// <remarks/>
        Invoice,
        
        /// <remarks/>
        InvoiceForAdvancePayment,
        
        /// <remarks/>
        InvoiceForPartialDelivery,
        
        /// <remarks/>
        SelfBilling,
        
        /// <remarks/>
        SubsequentCredit,
        
        /// <remarks/>
        SubsequentDebit,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderingPartyType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InvoiceRecipientType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BillerType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    public partial class AbstractPartyType {
        
        private string vATIdentificationNumberField;
        
        private FurtherIdentificationType[] furtherIdentificationField;
        
        private OrderReferenceType orderReferenceField;
        
        private AddressType addressField;
        
        private ContactType contactField;
        
        /// <remarks/>
        public string VATIdentificationNumber {
            get {
                return this.vATIdentificationNumberField;
            }
            set {
                this.vATIdentificationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FurtherIdentification")]
        public FurtherIdentificationType[] FurtherIdentification {
            get {
                return this.furtherIdentificationField;
            }
            set {
                this.furtherIdentificationField = value;
            }
        }
        
        /// <remarks/>
        public OrderReferenceType OrderReference {
            get {
                return this.orderReferenceField;
            }
            set {
                this.orderReferenceField = value;
            }
        }
        
        /// <remarks/>
        public AddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public ContactType Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("FurtherIdentification", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class FurtherIdentificationType {
        
        private string identificationTypeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string IdentificationType {
            get {
                return this.identificationTypeField;
            }
            set {
                this.identificationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OrderReferenceDetailType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("OrderReference", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class OrderReferenceType {
        
        private string orderIDField;
        
        private System.DateTime referenceDateField;
        
        private bool referenceDateFieldSpecified;
        
        private string descriptionField;
        
        /// <remarks/>
        public string OrderID {
            get {
                return this.orderIDField;
            }
            set {
                this.orderIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ReferenceDate {
            get {
                return this.referenceDateField;
            }
            set {
                this.referenceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceDateSpecified {
            get {
                return this.referenceDateFieldSpecified;
            }
            set {
                this.referenceDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Address", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class AddressType {
        
        private AddressIdentifierType[] addressIdentifierField;
        
        private string nameField;
        
        private string tradingNameField;
        
        private string streetField;
        
        private string pOBoxField;
        
        private string townField;
        
        private string zIPField;
        
        private CountryType countryField;
        
        private string[] phoneField;
        
        private string[] emailField;
        
        private string[] addressExtensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressIdentifier")]
        public AddressIdentifierType[] AddressIdentifier {
            get {
                return this.addressIdentifierField;
            }
            set {
                this.addressIdentifierField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string TradingName {
            get {
                return this.tradingNameField;
            }
            set {
                this.tradingNameField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string POBox {
            get {
                return this.pOBoxField;
            }
            set {
                this.pOBoxField = value;
            }
        }
        
        /// <remarks/>
        public string Town {
            get {
                return this.townField;
            }
            set {
                this.townField = value;
            }
        }
        
        /// <remarks/>
        public string ZIP {
            get {
                return this.zIPField;
            }
            set {
                this.zIPField = value;
            }
        }
        
        /// <remarks/>
        public CountryType Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Phone")]
        public string[] Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public string[] Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AddressExtension")]
        public string[] AddressExtension {
            get {
                return this.addressExtensionField;
            }
            set {
                this.addressExtensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("AddressIdentifier", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class AddressIdentifierType {
        
        private string addressIdentifierType1Field;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("AddressIdentifierType", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string AddressIdentifierType1 {
            get {
                return this.addressIdentifierType1Field;
            }
            set {
                this.addressIdentifierType1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Country", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class CountryType {
        
        private string countryCodeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token")]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Contact", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class ContactType {
        
        private string salutationField;
        
        private string nameField;
        
        private string[] phoneField;
        
        private string[] emailField;
        
        /// <remarks/>
        public string Salutation {
            get {
                return this.salutationField;
            }
            set {
                this.salutationField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Phone")]
        public string[] Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Email")]
        public string[] Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("RelatedDocument", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class RelatedDocumentType {
        
        private string invoiceNumberField;
        
        private System.DateTime invoiceDateField;
        
        private bool invoiceDateFieldSpecified;
        
        private DocumentTypeType documentTypeField;
        
        private bool documentTypeFieldSpecified;
        
        private string commentField;
        
        /// <remarks/>
        public string InvoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                this.invoiceNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InvoiceDateSpecified {
            get {
                return this.invoiceDateFieldSpecified;
            }
            set {
                this.invoiceDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public DocumentTypeType DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentTypeSpecified {
            get {
                return this.documentTypeFieldSpecified;
            }
            set {
                this.documentTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("AdditionalInformation", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class AdditionalInformationType {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Delivery", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class DeliveryType {
        
        private string deliveryIDField;
        
        private object itemField;
        
        private AddressType addressField;
        
        private ContactType contactField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string DeliveryID {
            get {
                return this.deliveryIDField;
            }
            set {
                this.deliveryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Date", typeof(System.DateTime), DataType="date")]
        [System.Xml.Serialization.XmlElementAttribute("Period", typeof(PeriodType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        public AddressType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public ContactType Contact {
            get {
                return this.contactField;
            }
            set {
                this.contactField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Period", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class PeriodType {
        
        private System.DateTime fromDateField;
        
        private System.DateTime toDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime FromDate {
            get {
                return this.fromDateField;
            }
            set {
                this.fromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime ToDate {
            get {
                return this.toDateField;
            }
            set {
                this.toDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Biller", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class BillerType : AbstractPartyType {
        
        private string invoiceRecipientsBillerIDField;
        
        /// <remarks/>
        public string InvoiceRecipientsBillerID {
            get {
                return this.invoiceRecipientsBillerIDField;
            }
            set {
                this.invoiceRecipientsBillerIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("InvoiceRecipient", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class InvoiceRecipientType : AbstractPartyType {
        
        private string billersInvoiceRecipientIDField;
        
        private string accountingAreaField;
        
        private string subOrganizationIDField;
        
        /// <remarks/>
        public string BillersInvoiceRecipientID {
            get {
                return this.billersInvoiceRecipientIDField;
            }
            set {
                this.billersInvoiceRecipientIDField = value;
            }
        }
        
        /// <remarks/>
        public string AccountingArea {
            get {
                return this.accountingAreaField;
            }
            set {
                this.accountingAreaField = value;
            }
        }
        
        /// <remarks/>
        public string SubOrganizationID {
            get {
                return this.subOrganizationIDField;
            }
            set {
                this.subOrganizationIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("OrderingParty", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class OrderingPartyType : AbstractPartyType {
        
        private string billersOrderingPartyIDField;
        
        /// <remarks/>
        public string BillersOrderingPartyID {
            get {
                return this.billersOrderingPartyIDField;
            }
            set {
                this.billersOrderingPartyIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Details", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class DetailsType {
        
        private string headerDescriptionField;
        
        private ItemListType[] itemListField;
        
        private string footerDescriptionField;
        
        /// <remarks/>
        public string HeaderDescription {
            get {
                return this.headerDescriptionField;
            }
            set {
                this.headerDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemList")]
        public ItemListType[] ItemList {
            get {
                return this.itemListField;
            }
            set {
                this.itemListField = value;
            }
        }
        
        /// <remarks/>
        public string FooterDescription {
            get {
                return this.footerDescriptionField;
            }
            set {
                this.footerDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("ItemList", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class ItemListType {
        
        private string headerDescriptionField;
        
        private ListLineItemType[] listLineItemField;
        
        private string footerDescriptionField;
        
        /// <remarks/>
        public string HeaderDescription {
            get {
                return this.headerDescriptionField;
            }
            set {
                this.headerDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ListLineItem")]
        public ListLineItemType[] ListLineItem {
            get {
                return this.listLineItemField;
            }
            set {
                this.listLineItemField = value;
            }
        }
        
        /// <remarks/>
        public string FooterDescription {
            get {
                return this.footerDescriptionField;
            }
            set {
                this.footerDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("ListLineItem", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class ListLineItemType {
        
        private string positionNumberField;
        
        private string[] descriptionField;
        
        private ArticleNumberType[] articleNumberField;
        
        private UnitType quantityField;
        
        private UnitPriceType unitPriceField;
        
        private ReductionAndSurchargeListLineItemDetailsType reductionAndSurchargeListLineItemDetailsField;
        
        private DeliveryType deliveryField;
        
        private OrderReferenceDetailType billersOrderReferenceField;
        
        private OrderReferenceDetailType invoiceRecipientsOrderReferenceField;
        
        private ClassificationType[] classificationField;
        
        private AdditionalInformationType[] additionalInformationField;
        
        private TaxItemType taxItemField;
        
        private decimal lineItemAmountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string PositionNumber {
            get {
                return this.positionNumberField;
            }
            set {
                this.positionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public string[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ArticleNumber")]
        public ArticleNumberType[] ArticleNumber {
            get {
                return this.articleNumberField;
            }
            set {
                this.articleNumberField = value;
            }
        }
        
        /// <remarks/>
        public UnitType Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public UnitPriceType UnitPrice {
            get {
                return this.unitPriceField;
            }
            set {
                this.unitPriceField = value;
            }
        }
        
        /// <remarks/>
        public ReductionAndSurchargeListLineItemDetailsType ReductionAndSurchargeListLineItemDetails {
            get {
                return this.reductionAndSurchargeListLineItemDetailsField;
            }
            set {
                this.reductionAndSurchargeListLineItemDetailsField = value;
            }
        }
        
        /// <remarks/>
        public DeliveryType Delivery {
            get {
                return this.deliveryField;
            }
            set {
                this.deliveryField = value;
            }
        }
        
        /// <remarks/>
        public OrderReferenceDetailType BillersOrderReference {
            get {
                return this.billersOrderReferenceField;
            }
            set {
                this.billersOrderReferenceField = value;
            }
        }
        
        /// <remarks/>
        public OrderReferenceDetailType InvoiceRecipientsOrderReference {
            get {
                return this.invoiceRecipientsOrderReferenceField;
            }
            set {
                this.invoiceRecipientsOrderReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Classification")]
        public ClassificationType[] Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalInformation")]
        public AdditionalInformationType[] AdditionalInformation {
            get {
                return this.additionalInformationField;
            }
            set {
                this.additionalInformationField = value;
            }
        }
        
        /// <remarks/>
        public TaxItemType TaxItem {
            get {
                return this.taxItemField;
            }
            set {
                this.taxItemField = value;
            }
        }
        
        /// <remarks/>
        public decimal LineItemAmount {
            get {
                return this.lineItemAmountField;
            }
            set {
                this.lineItemAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("ArticleNumber", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class ArticleNumberType {
        
        private ArticleNumberTypeType articleNumberType1Field;
        
        private bool articleNumberType1FieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ArticleNumberType", Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public ArticleNumberTypeType ArticleNumberType1 {
            get {
                return this.articleNumberType1Field;
            }
            set {
                this.articleNumberType1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ArticleNumberType1Specified {
            get {
                return this.articleNumberType1FieldSpecified;
            }
            set {
                this.articleNumberType1FieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    public enum ArticleNumberTypeType {
        
        /// <remarks/>
        PZN,
        
        /// <remarks/>
        GTIN,
        
        /// <remarks/>
        InvoiceRecipientsArticleNumber,
        
        /// <remarks/>
        BillersArticleNumber,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Quantity", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class UnitType {
        
        private string unitField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string Unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("UnitPrice", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class UnitPriceType {
        
        private decimal baseQuantityField;
        
        private bool baseQuantityFieldSpecified;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public decimal BaseQuantity {
            get {
                return this.baseQuantityField;
            }
            set {
                this.baseQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BaseQuantitySpecified {
            get {
                return this.baseQuantityFieldSpecified;
            }
            set {
                this.baseQuantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("ReductionAndSurchargeListLineItemDetails", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class ReductionAndSurchargeListLineItemDetailsType {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtherVATableTaxListLineItem", typeof(OtherVATableTaxType))]
        [System.Xml.Serialization.XmlElementAttribute("ReductionListLineItem", typeof(ReductionAndSurchargeBaseType))]
        [System.Xml.Serialization.XmlElementAttribute("SurchargeListLineItem", typeof(ReductionAndSurchargeBaseType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("OtherVATableTax", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class OtherVATableTaxType : TaxItemType {
        
        private string taxIDField;
        
        /// <remarks/>
        public string TaxID {
            get {
                return this.taxIDField;
            }
            set {
                this.taxIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OtherVATableTaxType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("TaxItem", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class TaxItemType {
        
        private decimal taxableAmountField;
        
        private TaxPercentType taxPercentField;
        
        private decimal taxAmountField;
        
        private bool taxAmountFieldSpecified;
        
        private AccountingCurrencyAmountType accountingCurrencyAmountField;
        
        private string commentField;
        
        /// <remarks/>
        public decimal TaxableAmount {
            get {
                return this.taxableAmountField;
            }
            set {
                this.taxableAmountField = value;
            }
        }
        
        /// <remarks/>
        public TaxPercentType TaxPercent {
            get {
                return this.taxPercentField;
            }
            set {
                this.taxPercentField = value;
            }
        }
        
        /// <remarks/>
        public decimal TaxAmount {
            get {
                return this.taxAmountField;
            }
            set {
                this.taxAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TaxAmountSpecified {
            get {
                return this.taxAmountFieldSpecified;
            }
            set {
                this.taxAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public AccountingCurrencyAmountType AccountingCurrencyAmount {
            get {
                return this.accountingCurrencyAmountField;
            }
            set {
                this.accountingCurrencyAmountField = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("TaxPercent", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class TaxPercentType {
        
        private string taxCategoryCodeField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token")]
        public string TaxCategoryCode {
            get {
                return this.taxCategoryCodeField;
            }
            set {
                this.taxCategoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("AccountingCurrencyAmount", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class AccountingCurrencyAmountType {
        
        private string currencyField;
        
        private decimal valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token")]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReductionAndSurchargeType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("ReductionListLineItem", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class ReductionAndSurchargeBaseType {
        
        private decimal baseAmountField;
        
        private decimal percentageField;
        
        private bool percentageFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string commentField;
        
        private ClassificationType classificationField;
        
        /// <remarks/>
        public decimal BaseAmount {
            get {
                return this.baseAmountField;
            }
            set {
                this.baseAmountField = value;
            }
        }
        
        /// <remarks/>
        public decimal Percentage {
            get {
                return this.percentageField;
            }
            set {
                this.percentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentageSpecified {
            get {
                return this.percentageFieldSpecified;
            }
            set {
                this.percentageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public ClassificationType Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Classification", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class ClassificationType {
        
        private string classificationSchemaField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string ClassificationSchema {
            get {
                return this.classificationSchemaField;
            }
            set {
                this.classificationSchemaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/", IncludeInSchema=false)]
    public enum ItemsChoiceType {
        
        /// <remarks/>
        OtherVATableTaxListLineItem,
        
        /// <remarks/>
        ReductionListLineItem,
        
        /// <remarks/>
        SurchargeListLineItem,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("BillersOrderReference", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class OrderReferenceDetailType : OrderReferenceType {
        
        private string orderPositionNumberField;
        
        /// <remarks/>
        public string OrderPositionNumber {
            get {
                return this.orderPositionNumberField;
            }
            set {
                this.orderPositionNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("ReductionAndSurchargeDetails", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class ReductionAndSurchargeDetailsType {
        
        private object[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtherVATableTax", typeof(OtherVATableTaxType))]
        [System.Xml.Serialization.XmlElementAttribute("Reduction", typeof(ReductionAndSurchargeType))]
        [System.Xml.Serialization.XmlElementAttribute("Surcharge", typeof(ReductionAndSurchargeType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName {
            get {
                return this.itemsElementNameField;
            }
            set {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Reduction", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class ReductionAndSurchargeType : ReductionAndSurchargeBaseType {
        
        private TaxItemType taxItemField;
        
        /// <remarks/>
        public TaxItemType TaxItem {
            get {
                return this.taxItemField;
            }
            set {
                this.taxItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/", IncludeInSchema=false)]
    public enum ItemsChoiceType1 {
        
        /// <remarks/>
        OtherVATableTax,
        
        /// <remarks/>
        Reduction,
        
        /// <remarks/>
        Surcharge,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Tax", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class TaxType {
        
        private TaxItemType[] taxItemField;
        
        private OtherTaxType[] otherTaxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaxItem")]
        public TaxItemType[] TaxItem {
            get {
                return this.taxItemField;
            }
            set {
                this.taxItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtherTax")]
        public OtherTaxType[] OtherTax {
            get {
                return this.otherTaxField;
            }
            set {
                this.otherTaxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("OtherTax", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class OtherTaxType {
        
        private string commentField;
        
        private decimal amountField;
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("PaymentMethod", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class PaymentMethodType {
        
        private string commentField;
        
        private object itemField;
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("NoPayment", typeof(NoPaymentType))]
        [System.Xml.Serialization.XmlElementAttribute("OtherPayment", typeof(OtherPaymentType))]
        [System.Xml.Serialization.XmlElementAttribute("PaymentCard", typeof(PaymentCardType))]
        [System.Xml.Serialization.XmlElementAttribute("SEPADirectDebit", typeof(SEPADirectDebitType))]
        [System.Xml.Serialization.XmlElementAttribute("UniversalBankTransaction", typeof(UniversalBankTransactionType))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("NoPayment", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class NoPaymentType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("OtherPayment", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class OtherPaymentType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("PaymentCard", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class PaymentCardType {
        
        private string primaryAccountNumberField;
        
        private string cardHolderNameField;
        
        /// <remarks/>
        public string PrimaryAccountNumber {
            get {
                return this.primaryAccountNumberField;
            }
            set {
                this.primaryAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        public string CardHolderName {
            get {
                return this.cardHolderNameField;
            }
            set {
                this.cardHolderNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("SEPADirectDebit", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class SEPADirectDebitType {
        
        private SEPADirectDebitTypeType typeField;
        
        private bool typeFieldSpecified;
        
        private string bICField;
        
        private string iBANField;
        
        private string bankAccountOwnerField;
        
        private string creditorIDField;
        
        private string mandateReferenceField;
        
        private System.DateTime debitCollectionDateField;
        
        private bool debitCollectionDateFieldSpecified;
        
        /// <remarks/>
        public SEPADirectDebitTypeType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
        
        /// <remarks/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
        
        /// <remarks/>
        public string BankAccountOwner {
            get {
                return this.bankAccountOwnerField;
            }
            set {
                this.bankAccountOwnerField = value;
            }
        }
        
        /// <remarks/>
        public string CreditorID {
            get {
                return this.creditorIDField;
            }
            set {
                this.creditorIDField = value;
            }
        }
        
        /// <remarks/>
        public string MandateReference {
            get {
                return this.mandateReferenceField;
            }
            set {
                this.mandateReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DebitCollectionDate {
            get {
                return this.debitCollectionDateField;
            }
            set {
                this.debitCollectionDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DebitCollectionDateSpecified {
            get {
                return this.debitCollectionDateFieldSpecified;
            }
            set {
                this.debitCollectionDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Type", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public enum SEPADirectDebitTypeType {
        
        /// <remarks/>
        B2C,
        
        /// <remarks/>
        B2B,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("UniversalBankTransaction", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class UniversalBankTransactionType {
        
        private AccountType[] beneficiaryAccountField;
        
        private PaymentReferenceType paymentReferenceField;
        
        private bool consolidatorPayableField;
        
        private bool consolidatorPayableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BeneficiaryAccount")]
        public AccountType[] BeneficiaryAccount {
            get {
                return this.beneficiaryAccountField;
            }
            set {
                this.beneficiaryAccountField = value;
            }
        }
        
        /// <remarks/>
        public PaymentReferenceType PaymentReference {
            get {
                return this.paymentReferenceField;
            }
            set {
                this.paymentReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public bool ConsolidatorPayable {
            get {
                return this.consolidatorPayableField;
            }
            set {
                this.consolidatorPayableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ConsolidatorPayableSpecified {
            get {
                return this.consolidatorPayableFieldSpecified;
            }
            set {
                this.consolidatorPayableFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("BeneficiaryAccount", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class AccountType {
        
        private string bankNameField;
        
        private BankCodeType bankCodeField;
        
        private string bICField;
        
        private string bankAccountNrField;
        
        private string iBANField;
        
        private string bankAccountOwnerField;
        
        /// <remarks/>
        public string BankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public BankCodeType BankCode {
            get {
                return this.bankCodeField;
            }
            set {
                this.bankCodeField = value;
            }
        }
        
        /// <remarks/>
        public string BIC {
            get {
                return this.bICField;
            }
            set {
                this.bICField = value;
            }
        }
        
        /// <remarks/>
        public string BankAccountNr {
            get {
                return this.bankAccountNrField;
            }
            set {
                this.bankAccountNrField = value;
            }
        }
        
        /// <remarks/>
        public string IBAN {
            get {
                return this.iBANField;
            }
            set {
                this.iBANField = value;
            }
        }
        
        /// <remarks/>
        public string BankAccountOwner {
            get {
                return this.bankAccountOwnerField;
            }
            set {
                this.bankAccountOwnerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("BankCode", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class BankCodeType {
        
        private string bankCodeType1Field;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("BankCodeType", Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="token")]
        public string BankCodeType1 {
            get {
                return this.bankCodeType1Field;
            }
            set {
                this.bankCodeType1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="integer")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("PaymentReference", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class PaymentReferenceType {
        
        private string checkSumField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string CheckSum {
            get {
                return this.checkSumField;
            }
            set {
                this.checkSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("PaymentConditions", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class PaymentConditionsType {
        
        private System.DateTime dueDateField;
        
        private bool dueDateFieldSpecified;
        
        private DiscountType[] discountField;
        
        private decimal minimumPaymentField;
        
        private bool minimumPaymentFieldSpecified;
        
        private string commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime DueDate {
            get {
                return this.dueDateField;
            }
            set {
                this.dueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DueDateSpecified {
            get {
                return this.dueDateFieldSpecified;
            }
            set {
                this.dueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Discount")]
        public DiscountType[] Discount {
            get {
                return this.discountField;
            }
            set {
                this.discountField = value;
            }
        }
        
        /// <remarks/>
        public decimal MinimumPayment {
            get {
                return this.minimumPaymentField;
            }
            set {
                this.minimumPaymentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MinimumPaymentSpecified {
            get {
                return this.minimumPaymentFieldSpecified;
            }
            set {
                this.minimumPaymentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ebinterface.at/schema/5p0/")]
    [System.Xml.Serialization.XmlRootAttribute("Discount", Namespace="http://www.ebinterface.at/schema/5p0/", IsNullable=false)]
    public partial class DiscountType {
        
        private System.DateTime paymentDateField;
        
        private decimal baseAmountField;
        
        private bool baseAmountFieldSpecified;
        
        private decimal percentageField;
        
        private bool percentageFieldSpecified;
        
        private decimal amountField;
        
        private bool amountFieldSpecified;
        
        private string commentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PaymentDate {
            get {
                return this.paymentDateField;
            }
            set {
                this.paymentDateField = value;
            }
        }
        
        /// <remarks/>
        public decimal BaseAmount {
            get {
                return this.baseAmountField;
            }
            set {
                this.baseAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BaseAmountSpecified {
            get {
                return this.baseAmountFieldSpecified;
            }
            set {
                this.baseAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Percentage {
            get {
                return this.percentageField;
            }
            set {
                this.percentageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PercentageSpecified {
            get {
                return this.percentageFieldSpecified;
            }
            set {
                this.percentageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
    }
}
