//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 4.0.30319.34014.
// 
#pragma warning disable 1591

namespace ebIServices.at.gv.bmf.finanzonline1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="uidAbfrageBinding", Namespace="https://finanzonline.bmf.gv.at/fon/ws/uid")]
    public partial class uidAbfrageService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback uidAbfrageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public uidAbfrageService() {
            this.Url = global::ebIServices.Properties.Settings.Default.ebIServices_at_gv_bmf_finanzonline1_uidAbfrageService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event uidAbfrageCompletedEventHandler uidAbfrageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("uidAbfrage", RequestElementName="uidAbfrageRequest", RequestNamespace="https://finanzonline.bmf.gv.at/fon/ws/uid", ResponseNamespace="https://finanzonline.bmf.gv.at/fon/ws/uid", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("rc")]
        public string uidAbfrage(string sessionid, string tid, string benid, string uid_tn, string uid, string stufe, out string name, out string adrz1, out string adrz2, out string adrz3, out string adrz4, out string adrz5, out string adrz6) {
            object[] results = this.Invoke("uidAbfrage", new object[] {
                        sessionid,
                        tid,
                        benid,
                        uid_tn,
                        uid,
                        stufe});
            name = ((string)(results[1]));
            adrz1 = ((string)(results[2]));
            adrz2 = ((string)(results[3]));
            adrz3 = ((string)(results[4]));
            adrz4 = ((string)(results[5]));
            adrz5 = ((string)(results[6]));
            adrz6 = ((string)(results[7]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void uidAbfrageAsync(string sessionid, string tid, string benid, string uid_tn, string uid, string stufe) {
            this.uidAbfrageAsync(sessionid, tid, benid, uid_tn, uid, stufe, null);
        }
        
        /// <remarks/>
        public void uidAbfrageAsync(string sessionid, string tid, string benid, string uid_tn, string uid, string stufe, object userState) {
            if ((this.uidAbfrageOperationCompleted == null)) {
                this.uidAbfrageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuidAbfrageOperationCompleted);
            }
            this.InvokeAsync("uidAbfrage", new object[] {
                        sessionid,
                        tid,
                        benid,
                        uid_tn,
                        uid,
                        stufe}, this.uidAbfrageOperationCompleted, userState);
        }
        
        private void OnuidAbfrageOperationCompleted(object arg) {
            if ((this.uidAbfrageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uidAbfrageCompleted(this, new uidAbfrageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void uidAbfrageCompletedEventHandler(object sender, uidAbfrageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uidAbfrageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal uidAbfrageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string adrz1 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string adrz2 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string adrz3 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
        
        /// <remarks/>
        public string adrz4 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[5]));
            }
        }
        
        /// <remarks/>
        public string adrz5 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[6]));
            }
        }
        
        /// <remarks/>
        public string adrz6 {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[7]));
            }
        }
    }
}

#pragma warning restore 1591